config/routes.rb
Iter8::Application.routes.draw do
  devise_for :users

  resources :iterables do 
    collection { post :sort}
  end

  resources :iterables, shallow: true do
    resources :iterablesusers, :only => [:new, :create, :destroy]
    resources :posts, shallow: true do
      resources :actions
      resources :comments
    end
  end

  root :to => "pages#landing"

end

app/models/action.rb
class Action < ActiveRecord::Base
  attr_accessible :action, :iterable_id

  belongs_to :post
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment
  belongs_to :post
  belongs_to :user
  
end

app/models/iterable.rb
class Iterable < ActiveRecord::Base
  attr_accessible :name, :position, :is_header
  has_and_belongs_to_many :users
  has_many :posts

end

app/models/iterables_users.rb
class IterablesUsers < ActiveRecord::Base
  attr_accessible :iterable_id, :user_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :post, :user_id
  has_many :comments
  has_many :actions
  belongs_to :iterable
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_and_belongs_to_many :iterables
  has_many :posts
  has_many :comments

  
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController

	def index
	end

	def new
	end

	def create
		@post = Post.find(params[:post_id])
		@action = @post.actions.build(:action => params[:new_action])
		@iterable = current_user.iterables.find(@post.iterable_id)
		if @action.save
			flash[:success] = "Action created!"
			redirect_to iterable_path(@iterable)
		else
			flash[:notice] = "Unable to create action"
			redirect_to new_post_comment_path(@post)
		end
	end

	def edit
	end

	def update
	end

	def destroy
		@action = Action.find(params[:action_id]).destroy
		respond_to do |format|
			format.html { flash[:success] = "Action deleted!"
						  redirect_to iterable_path(params[:id])}
			format.js
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
	end

	def show
	end

	def new
	end

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.build(:comment => params[:new_comment])
		@iterable = current_user.iterables.find(@post.iterable_id)
		if @comment.save
			flash[:success] = "Comment posted!"
			redirect_to iterable_path(@iterable)
			@iterable.touch
		else
			flash[:notice] = "Unable to post comment"
			redirect_to new_post_comment_path(@post)
		end
	end

	def edit
	end

	def update
	end

	def destroy
		@comment = Comment.find(params[:comment_id])
		if @comment.destroy
			flash[:success] = "Comment deleted!"
		else
			flash[:notice] = "Unable to delete comment"
		end
		redirect_to iterable_path(params[:id])
	end
	
end

app/controllers/iterables_controller.rb
class IterablesController < ApplicationController

	def index
		@iterables = current_user.iterables.order("position")
	end

	def show
		@iterable = current_user.iterables.find(params[:id])
		@users = @iterable.users.all
		@posts = @iterable.posts.find(:all, :order => "created_at DESC")
		@post = @iterable.posts.new
	end

	def new
		@iterable = current_user.iterables.new
	end

	def create
		if current_user.iterables.create!(:name => params[:iterable][:name], :position => current_user.iterables.last.position + 1, :is_header => params[:iterable][:is_header])
			flash[:success] = "Iterable created!"
			redirect_to iterables_path
		else
			flash[:notice] = "Could not create iterable"
			redirect_to new_iterable_path
		end
	end

	def edit
		@iterable = current_user.iterables.find(params[:id])
	end

	def update
		@iterable = current_user.iterables.find(params[:id])
		if @iterable.update_attributes(params[:iterable])
			flash[:success] = "Iterable name updated!"
			redirect_to iterables_path
		else
			flash[:notice] = "Could not update iterable name"
			redirect_to edit_iterable_path(@iterable)
		end
	end

	def destroy
		@iterable = Iterable.find(params[:id]).destroy
		respond_to do |format|
			format.html {flash[:success] = "Iterable deleted!"
						 redirect_to iterables_path}
			format.js
		end
	end

	def sort
		params[:iterable].each_with_index do |id, index|
			Iterable.update_all({position: index+1}, {id: id})
		end
		render nothing: true
	end

end

app/controllers/iterablesusers_controller.rb
class IterablesusersController < ApplicationController

	def new
	end

	def create
		@iterable = current_user.iterables.find(params[:iterable_id])
		if @iterable.users << User.find_by_email(params[:new_user])
			flash[:success] = "User added!"
			redirect_to iterable_path(@iterable)
		else
			flash[:notice] = "Could not add user"
			redirect_to new_iterable_iterablesuser_path
		end
	end

	def destroy
		@iterable = current_user.iterables.find(params[:id])
		@user_deleted = User.find(params[:user_deleted])
		if @iterable.users.delete(@user_deleted)
			flash[:success] = "User deleted!"
		else
			flash[:notice] = "Could not delete user"
		end
		redirect_to iterable_path(@iterable)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def landing
		if user_signed_in?
			redirect_to iterables_path
		end
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
	end

	def create
		@iterable = current_user.iterables.find(params[:iterable_id])
		@iterable.posts.create!(:post => params[:post][:post], :user_id => current_user.id)
		@post = @iterable.posts.find_all_by_post(params[:post][:post]).last
		respond_to do |format|
			format.html { flash[:success] = "Post created!"
						  redirect_to iterable_path(@iterable) }
			format.js
		end
	end

	def edit
	end

	def update
	end

	def destroy
		@post = Post.find(params[:id]).destroy
		respond_to do |format|
			format.html { flash[:success] = "Post deleted!"
						  redirect_to iterable_path(@post.iterable_id) }
			format.js
		end
	end
	
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/iterables_helper.rb
module IterablesHelper
end

app/helpers/iterablesusers_helper.rb
module IterablesusersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/actions/destroy.js.erb
$('#action_<%= @action.id %>').remove();

app/views/actions/new.html.erb
<%= form_tag({:controller => "actions", :action => "create"}) do %>
  <%= label_tag(:new_action, "Action") %>
  <%= text_area_tag(:new_action) %>
  <%= submit_tag("Act!") %>
<% end %>

app/views/comments/new.html.erb
<%= form_tag({:controller => "comments", :action => "create"}) do %>
  <%= label_tag(:new_comment, "Comment") %>
  <%= text_field_tag(:new_comment) %>
  <%= submit_tag("Critique!") %>
<% end %>

app/views/iterables/destroy.js.erb
$('#iterable_<%= @iterable.id %>').remove();

app/views/iterables/edit.html.erb
<%= form_for @iterable, :url=>iterable_path(@iterable), :html=>{:method=>:put} do |f| %>
  <legend>Change Iterable Name</legend>
  <%= f.label :name, "New name" %>
  <%= f.text_field :name %>
  <%= f.label :tag_list, "Tags" %>
  <%= f.text_field :tag_list %>
  <%= f.submit "Start Iterating", :class => "btn btn-medium" %>
<% end %>

<%= @tags %>

app/views/iterables/index.html.erb
<div class="header">
	<h1>All Iterables</h1>
	<%= link_to "New Iterable", new_iterable_path(:is_header => false), :class => "btn btn-primary btn-medium" %>
	<%= link_to "New Header", new_iterable_path(:is_header => true), :class => "btn btn-primary btn-medium header" %>
	<hr>
</div>
<ul id="iterables" data-update-url="<%= sort_iterables_url %>">
<% for iterable in @iterables %>
	<%= content_tag_for :li, iterable do %>
		<% if iterable.is_header == true %>
			<div class="list-header">
				<%= iterable.name %> 
				<%= link_to "x", iterable_path(iterable), :method => :delete, :class => "pull-right", :confirm => "Are you sure?", :remote => true%>
			</div>
		<% else %>
			<%= link_to iterable.name, iterable_path(iterable) %>
			<%= link_to "edit", edit_iterable_path(iterable), :class => "edit-button" %>
			<%= link_to "x", iterable_path(iterable), :method => :delete, :class => "pull-right", :confirm => "Are you sure?", :remote => true%>
		<% end %>
	<% end %>
<% end %>
</ul>

app/views/iterables/new.html.erb
<%= form_for @iterable, :is_header => params[:is_header] do |f| %>
  <legend>Create New Iterable</legend>
  <%= f.label :name, "Name" %>
  <%= f.text_area :name, :rows => "3" %>
  <%= f.hidden_field :is_header, :value => params[:is_header] %>
  <%= f.submit "Start Iterating", :class => "btn btn-medium" %>
<% end %>

app/views/iterables/show.html.erb
<h3><%= @iterable.name %></h3>

<div class="well">
<% for post in @posts %>
	<ul>
		<% for action in post.actions.all %>
			<li id="action_<%= action.id %>">
				<%= action.action %>
				<%= link_to "show", post_path(post) %>
				<%= link_to "x", action_path(:action_id => action.id), :method => "delete", :confirm => "Are you sure?" , :remote => true %>
			</li>
		<% end %>
	</ul>
<% end %>
</div>

<%= render :partial => "shared/post-form" %>

<div id="post-area">
	<%= render :partial => "shared/post", :collection => @posts %>
</div>

<div class="side-column well span2">

	<div class="new-user-button"> <%= link_to "Add New User", new_iterable_iterablesuser_path(@iterable) %> </div>

	<% for user in @users %>
		<div class="inner-container">
			<p><%= user.email %></p>
			<% if current_user.id != user.id %>	
				<%= link_to "x", iterablesuser_path(:user_deleted => user.id), :method => "delete", :class => "delete-button", :confirm => "Are you sure?" %>
			<% end %>
		</div>
	<% end %>
	</div>

app/views/iterablesusers/new.html.erb
<%= form_tag({:controller => "iterablesusers", :action => "create"}) do %>
  <%= label_tag(:new_user, "User's email:") %>
  <%= text_field_tag(:new_user) %>
  <%= submit_tag("Add User!") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iter8</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="navbar">
  <div class="navbar-inner">
    <div class="span8 offset2">
    <%= link_to "Iter8", root_path, :class => "brand" %>
    <ul class="nav pull-right">
    <% if current_user %>
      <li><%= link_to "Account", edit_user_registration_path %></li>
	    <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
    <% else %>
      <li><%= link_to "Sign In", new_user_session_path %></li>
	    <li><%= link_to "Register", new_user_registration_path %></li>
    <% end %>
    </ul>
  </div>
  </div>
</div>

<div class="span6 offset3">
	<%= yield %>
</div>

</body>
</html>

app/views/pages/landing.html.erb
This is the landing page.

app/views/posts/create.js.erb
$('#post-area').prepend('<%= j render partial: "shared/special-post", object: @post %>');

app/views/posts/destroy.js.erb
$('#post_<%= @post.id%>').remove();

app/views/posts/index.html.erb
Hello!!!!

app/views/posts/new.html.erb
<%= form_tag({:controller => "posts", :action => "create"}) do %>
  <%= label_tag(:new_post, "Description") %>
  <%= text_area_tag(:new_post) %>
  <%= submit_tag("Iterate!") %>
<% end %>

app/views/posts/show.html.erb
<p><%= @post.post %></p>

app/views/shared/_comments.html.erb
<%= form_tag({:controller => "comments", :action => "create"}) do %>
  <%= label_tag(:new_comment, "Comment") %>
  <%= text_area_tag(:new_comment) %>
  <%= submit_tag("Critique!") %>
<% end %>

app/views/shared/_post-form.html.erb
<div class="post-form">
<%= form_for [@iterable, @post], remote: true do |f|%>
  <%= f.text_area :post, :class => "span6", :rows => "3", :placeholder => "What would you like to iterate on today?" %>
  <%= f.submit "Iterate!", :class => "btn btn-info pull-right " %>
<% end %>
</div>

app/views/shared/_post.html.erb
<div class='post' id='post_<%= post.id %>'>
	<div class='timestamp span1'>
		<h5><%= post.created_at.in_time_zone('Singapore').strftime('%l:%M%p') %></h5>
	</div>
	<div class='content span5'>
		<p>
		   <%= post.post %> 
		</p>
		<p>
			<%= link_to 'action!', new_post_action_path(post), :class => 'action-link' %> |
			<%= link_to 'delete', post_path(post), :method => :delete, :confirm => "Are you sure?" , :remote => true %>
		</p>
	</div>
</div>

app/views/shared/_special-post.html.erb
<div class='post'>
	<div class='timestamp span1'>
		<h5><%= @post.created_at.in_time_zone('Singapore').strftime('%l:%M%p') %></h5>
	</div>
	<div class='content span5'>
		<p>
		   <%= @post.post %> 
		</p>
		<p>
			<%= link_to 'action!', new_post_action_path(@post), :class => 'action-link' %> |
			<%= link_to 'delete', post_path(@post), :method => :delete , :confirm => "Are you sure?" , :remote => true  %>
		</p>
	</div>
</div>